### ISSUE TITLE
使用本地配置启动报错

### ISSUE THREAD

**Issue by dyingbleed** [gomcarter/developer#5]
修改 pom.xml 文件，修改为本地模式 `<artifactId>config-center-local</artifactId>`，启动服务，提示找不到类 `com.alibaba.nacos.client.config.utils.MD5`。

错误原因：`com.gomcarter.developer.service.InterfacesService` 中使用了`com.alibaba.nacos.client.config.utils.MD5` Hash 函数。

**Comment by gomcarter** [comment]
https://github.com/gomcarter/developer/issues/5
