### ISSUE TITLE
ApiInterface中不存在getReturnClassName和getParameterClassNames方法，导致本地启动报错

### ISSUE THREAD

**Issue by bitlin** [gomcarter/developer#7]
package com.gomcarter.developer.service; 
IInterfacesServicenterfacesService类文件中有引用ApiInterface中的getReturnClassName和getParameterClassNames方法，但是在ApiInterface中不存在，报错

**Comment by gomcarter** [comment]
抱歉，当前代码引用的jar没有发布到中央仓库，导致本地代码有错误。
对应的jar代码在：https://github.com/gomcarter/frameworks/tree/master/interfaces-starter，如需启动，可以考虑本地maven install 之后能用。

**Comment by gomcarter** [comment]
> package com.gomcarter.developer.service;
> IInterfacesServicenterfacesService类文件中有引用ApiInterface中的getReturnClassName和getParameterClassNames方法，但是在ApiInterface中不存在，报错

抱歉，当前代码引用的jar没有发布到中央仓库，导致本地代码有错误。
对应的jar代码在：https://github.com/gomcarter/frameworks/tree/master/interfaces-starter
，如需启动，可以考虑本地maven install 之后能用。
